# Generated by Django 4.1.7 on 2023-06-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUIT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='tags',
            field=models.ManyToManyField(to='PRODUIT.tags'),
        ),
    ]
