# Generated by Django 4.1.7 on 2023-06-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUIT', '0002_alter_produit_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='date_creation',
        ),
    ]
