# Generated by Django 4.1.7 on 2023-06-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUIT', '0003_remove_produit_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
