# Generated by Django 4.1.7 on 2023-06-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUIT', '0004_produit_quantite_stock_alter_tags_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
