# Generated by Django 4.1.5 on 2023-06-29 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUIT', '0005_alter_tags_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PRODUIT.unite'),
        ),
    ]
