# Generated by Django 4.1.7 on 2023-06-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PRODUIT', '0004_produit_quantite_stock_alter_tags_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_stock', models.FloatField()),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PRODUIT.produit')),
            ],
        ),
    ]
