# Generated by Django 4.1.7 on 2023-06-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='quantite_stock',
            field=models.FloatField(null=True),
        ),
    ]
