# Generated by Django 4.1.7 on 2023-06-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0002_alter_inventaire_quantite_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='quantite_stock',
            field=models.FloatField(default=0),
        ),
    ]
