# Generated by Django 4.1.3 on 2022-12-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
