# Generated by Django 4.1.7 on 2023-06-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENT', '0002_client_prenom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
    ]
