# Generated by Django 4.1.7 on 2023-06-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENT', '0003_alter_client_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
    ]
