# Generated by Django 4.1.7 on 2023-06-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUIT', '0004_produit_quantite_stock_alter_tags_nom'),
        ('ACHAT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='montant_total',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='status',
            field=models.CharField(choices=[('livraison en cours', 'Livraison en cours'), ('non livré', 'Non livré'), ('livré', 'Livré')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ACHAT.fournisseur'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PRODUIT.produit'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
