# Generated by Django 4.1.5 on 2023-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACHAT', '0002_achat_montant_total_fournisseur_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='status',
        ),
        migrations.AddField(
            model_name='achat',
            name='status',
            field=models.CharField(choices=[('livraison en cours', 'Livraison en cours'), ('non livré', 'Non livré'), ('livré', 'Livré')], max_length=200, null=True),
        ),
    ]
