# Generated by Django 4.1.5 on 2023-06-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACHAT', '0003_remove_fournisseur_status_achat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
