# Generated by Django 4.1.7 on 2023-06-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMANDE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
