# Generated by Django 4.1.7 on 2023-06-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMMANDE', '0003_remove_commande_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
